### ISSUE TITLE
Error: file_put_contents(/m2/app/etc/vendor_path.php): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by mcspronko** [extdn/github-actions-m2#115]
The ExtDN M2 PHPStan workflow returns the below error:
```
Error: file_put_contents(/m2/app/etc/vendor_path.php): Failed to open stream: No such file or directory
Use the `composer fund` command to find out more!

In PluginManager.php(278) : eval()'d code line 323:
                                                                               
  file_put_contents(/m2/app/etc/vendor_path.php): Failed to open stream: No s  
  uch file or directory                                                        
```

Configuration used:
```yml
name: ExtDN M2 PHPStan
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    phpstan:
        name: M2 PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: extdn/github-actions-m2/magento-phpstan/8.1@master
              with:
                  composer_name: pronko/workflow-tests-magento-module
```

Am I missing something in the yaml file or there is an issue with the workflow?

**Comment by sprankhub** [comment]
This configuration works for us: https://github.com/customgento/CustomGento_Invoice-m2/blob/3959c742e9147d7dc7afc4a05ade4dc4124d1619/.github/workflows/phpstan.yml

Could you try with a similar one?

**Comment by mcspronko** [comment]
Thanks @sprankhub I will try and let you know.

**Comment by mcspronko** [comment]
Hi @sprankhub thank you for the suggestion, works like a charm!

**Comment by sprankhub** [comment]
Okay, interesting :D So internally, this uses https://github.com/customgento/m2-github-actions/blob/main/.github/workflows/phpstan.yml. The only real difference I see is that it uses PHP 8.2 insteaf of PHP 8.1... :thinking:

**Comment by mcspronko** [comment]
Interestingly, it worked fine with the https://github.com/customgento/m2-github-actions/blob/main/.github/workflows/phpstan.yml configuration, but when I tried to add a composer_name it fails with the same error:
```yml
name: ExtDN M2 PHPStan
on: [push, pull_request]

jobs:
    phpstan:
        name: M2 PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: extdn/github-actions-m2/magento-phpstan/8.2@master
              with:
                  composer_name: pronko/workflow-tests-magento-module
```
```
Error: file_put_contents(/m2/app/etc/vendor_path.php): Failed to open stream: No such file or directory
Use the `composer fund` command to find out more!

In PluginManager.php(278) : eval()'d code line 323:
                                                                               
  file_put_contents(/m2/app/etc/vendor_path.php): Failed to open stream: No s  
  uch file or directory                                                        
```
