### ISSUE TITLE
Why does the integration build work without credentials but not the unit test build?

### ISSUE THREAD

**Issue by Vinai** [extdn/github-actions-m2#22]
The unit test build requires setting `secrets.MAGENTO_MARKETPLACE_USERNAME` and `secrets.MAGENTO_MARKETPLACE_PASSWORD`.

For myself as the maintainer that is not a problem, but it means I have to ask every contributor to set up the secrets when they open a PR...
I'm just wondering, shouldn't it be possible to execute the build without the credentials, since it also works for the integration test build?

**Comment by Vinai** [comment]
I just found `--repository=https://repo-magento-mirror.fooman.co.nz/` is used for the integration test build, but not for the unit test build.
Is there a reason to stick with the "official" repo for the unit tests?

**Comment by Vinai** [comment]
By the way, THANK YOU @fooman for setting up the mirror!

**Comment by jissereitsma** [comment]
I think this is just work in progress. The first step into improving things was to add secrets, so that the secrets could be used in different actions - this is what I'm using already, but indeed, the secrets will not work with Pull Requests :( For that matter, there is no way to share an environment variable ("secret") with others than the contributors of the project.

However, the thing that you bump into is more a flaw in the documentation, than the actual workflow files. In the docs, it is mentioned to use the following snippet:
```yaml
jobs:
    env:
          MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
          MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
```
But it is quite common that people fill in the details differently. The dependency in the workflow files is with the environment variable. The way to fill in that environment variable - for instance, using secrets or hard-coded - is up to you. (Obviously, hard-coded is not pretty.)

```yaml
jobs:
    env:
          MAGENTO_MARKETPLACE_USERNAME: foo
          MAGENTO_MARKETPLACE_PASSWORD: bar
```

But you already changed the topic: Why not use the mirror? Good point - I see no reason not to. I'm going to fix that right away. Ideally, with a switch `USE_FOOMAN_REPO` which defaults to `true`.
