### ISSUE TITLE
[Question] Autoload errors with phpstan workflows.

### ISSUE THREAD

**Issue by Sental** [extdn/github-actions-m2#34]
Hello,

I'm getting a lot of "Class X was not found while trying to analyse it  - autoloading is probably not configured properly. Learn more at https://phpstan.org/user-guide/autoloading" while using extdn/github-actions-m2/magento-phpstan@master.

I don't have any problems with the coding standard workflow or when I run phpcs locally.

Is this a configuration issue with my workflow, my project or something that needs updating here?

Workflow yml file content:
```
name: ExtDN M2 PHPStan

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-phpstan@master
        with:
          composer_name: reessolutions/cms-transfer
```
