### ISSUE TITLE
[FEAT] Allow integration tests using EE version

### ISSUE THREAD

**Issue by damienwebdev** [extdn/github-actions-m2#42]

**Comment by damienwebdev** [comment]
This was originally addressed by #48 but is not reverted by 6f754f357439912489376b54ae4df52e4dc6c591 and 4885780b85b01e0e1b0920c54ea7b21e48b76550

I don't really understand why there are 3 different variables for $MAGENTO_PROJECT_NAME ($PROJECT_NAME, $INPUT_PROJECT_NAME)

```bash
INPUT_PROJECT_NAME="magento/project-enterprise-edition" && MAGENTO_PROJECT_NAME=""
test -z "${MAGENTO_PROJECT_NAME}" || MAGENTO_PROJECT_NAME=$INPUT_PROJECT_NAME
test -z "$MAGENTO_PROJECT_NAME" && MAGENTO_PROJECT_NAME="magento/project-community-edition"
echo $MAGENTO_PROJECT_NAME
```

**Comment by jissereitsma** [comment]
Yes and no. By using `env` it works for me. By using `with` it does not work for me. Which YAML are you using?

**Comment by damienwebdev** [comment]
```yml
  steps:
      - uses: actions/checkout@v2
      - name: M2 Integration Tests with Magento 2 (Php7.4)
        uses: extdn/github-actions-m2/magento-integration-tests/7.4
        with:
          module_name: MyPackage
          composer_name: namespace/package
          ce_version: '2.4.3'
          project_name: magento/project-enterprise-edition
        env:
          REPOSITORY_URL: https://repo.magento.com/
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
```
