### ISSUE TITLE
Add PHP 8.1 support for PHPStan

### ISSUE THREAD

**Issue by jissereitsma** [extdn/github-actions-m2#68]
Add PHP version infrastructure similar to the approach with unit tests and integration tests. Add PHP 8.1, following from that. Make sure that the workflows in this repository are also picking up on new commits and/or PRs, so that Docker images are built automatically. Ask @sprankhub to do the work.

**Comment by sprankhub** [comment]
Nice try, @jissereitsma :sweat_smile: 

> Make sure that the workflows in this repository are also picking up on new commits and/or PRs, so that Docker images are built automatically.

At least this should be fixed already. Images are built automatically already on new relevant pushes.

**Comment by jissereitsma** [comment]
The PHPStan GitHub Action is updated to include a PHP version. Little sample:

```yaml
name: ExtDN M2 PHPStan
on: [push, pull_request]

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-phpstan/8.1@master
        with:
          composer_name: ${{ secrets.COMPOSER_NAME }}
```

Mainly the action usage of `extdn/github-actions-m2/magento-phpstan@master` should switch to `extdn/github-actions-m2/magento-phpstan/8.1@master` (or PHP 7.3 or PHP 7.4).
