### ISSUE TITLE
Missing Env Variables

### ISSUE THREAD

**Issue by sprankhub** [extdn/github-actions-m2#70]
As part of https://github.com/extdn/github-actions-m2/pull/69, we encountered that there are quite some input variables, which are not passed into the Docker container. https://github.com/extdn/github-actions-m2/blob/4091e3ae8e47b4fdaa049a9c64a088c1d06d02f1/magento-integration-tests/entrypoint.sh uses the following inputs, which are not passed into the Docker container here:

https://github.com/extdn/github-actions-m2/blob/4091e3ae8e47b4fdaa049a9c64a088c1d06d02f1/magento-integration-tests/8.1/action.yml#L44-L49

* `INPUT_ELASTICSEARCH`
* `INPUT_PHPUNIT_FILE`
* `INPUT_COMPOSER_VERSION`
* `INPUT_REPOSITORY_URL`
* `INPUT_PRE_PROJECT_SCRIPT`
* `INPUT_POST_PROJECT_SCRIPT`
* `INPUT_MAGENTO_PRE_INSTALL_SCRIPT`
* `INPUT_MAGENTO_POST_INSTALL_SCRIPT`

Wouldn't all these variables need to be passed as well? Am I missing something?

/cc @jissereitsma

**Comment by jissereitsma** [comment]
Hmm, I understand that earlier PR #69 better now. The thing is that both inputs and env variables are supposed to be supported in your own workflow YAML. For instance, if I would create the following workflow (for static tests, but it illustrates the idea):
```yaml
on: [push]
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-coding-standard/8.1@master
        with:
          phpcs_severity: 6
```
then it would equal the following:
```yaml
on: [push]
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-coding-standard/8.1@master
        env:
          PHPCS_SEVERITY: 6
```
which again equals:
```yaml
name: ExtDN Static Tests
on: [push]
env:
  PHPCS_SEVERITY: 6
jobs:
  static:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-coding-standard/8.1@master
```

In other words, either you would define an input `foobar` (using `with` in your own workflow YAML) which translates within the GitHub Action of ExtDN to `INPUT_FOOBAR` or you would define an env `FOOBAR`. And next, the GitHub Action of ExtDN, simply sees if `FOOBAR` is empty and then uses `INPUT_FOOBAR` as an alternative. At least this is what the original scripts set up by @fooman did and I always just copied things from it.

Following from this, in the Integration Test scripts, the variable `ELASTICSEARCH` for instance is usable via `env` (https://github.com/extdn/github-actions-m2/blob/4091e3ae8e47b4fdaa049a9c64a088c1d06d02f1/magento-integration-tests/entrypoint.sh#L11). But (!) because its definition is missing in the `action.yml`, people might not know about this. Plus, because the variable is not defined as input in `action.yml`, the variable is never allowed as input either. Therefore the `INPUT_ELASTICSEARCH` variable will never do anything: This is incomplete and should be fixed.

As I see it, there are 2 issues:

1) All input variables that are mentioned in the `entrypoint.sh` script, should also be mentioned in `action.yml` (complete with comments and optional flag) under `input`. This allows better documenting of what is done. This needs to be done for variables like `ELASTICSEARCH` (input `elasticsearch`) and so on.

2) Currently, users might have implemented either `env` or `with` in their own workflow YAML. And because of this, I think that both should work. But this actually means that the `action.yml` should **not** copy the input variable into an env variable (like `ELASTICSEARCH: ${{ inputs.elasticsearch }}`) as suggested by @BorisovskiP . This will break the workflow of people that are now using the `env` variables to configure things (I'm using both). This would require that commit 
https://github.com/extdn/github-actions-m2/commit/96abbdf5d7cbe0f1523a79a4798599419cfe293e is undone.
