### ISSUE TITLE
PHPStan. Add support to change repository url

### ISSUE THREAD

**Issue by rybkinevg** [extdn/github-actions-m2#80]
Hello!

I store my modules as a packages in the private packagist and I faced the problem with PHPStan action: when action is running it tries to download package dependency and falls down with error, cause this package is in the private packagist.

Example of the `composer.json` file: 

```json
{
    "name": "vedor/module-foo-bar",
    "type": "magento2-module",
    "require": {
        "magento/framework": "*",
        "vendor/module-from-private-packagist": "*"
    },
}

```

As I can see, the repository variable is installing through the [Dockerfile:7.4 at line 4](https://github.com/extdn/github-actions-m2/blob/master/magento-phpstan/Dockerfile:7.4#L4), it would be great to pass the `REPOSITORY_URL` env variable such as we are  installing it into integration tests action like this:

```yaml
jobs:
  integration-tests:
    env:
      REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
```
