### ISSUE TITLE
Error Running Copy/Paste Detector

### ISSUE THREAD

**Issue by navarr** [extdn/github-actions-m2#81]
Job code:

```yaml
  phpcpd:
    name: Magento Copy/Paste Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-copy-paste-detector@master
```

Error:

> Pull down action image 'extdn/magento-copy-paste-detector-action:latest'
  /usr/bin/docker pull extdn/magento-copy-paste-detector-action:latest
  Error response from daemon: pull access denied for extdn/magento-copy-paste-detector-action, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning: Docker pull failed with exit code 1, back off 9.9[2](https://github.com/swiftotter/anomaly-detective-magento2/actions/runs/4226282278/jobs/7339563782#step:2:2)2 seconds before retry.
  /usr/bin/docker pull extdn/magento-copy-paste-detector-action:latest
  Error response from daemon: pull access denied for extdn/magento-copy-paste-detector-action, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning: Docker pull failed with exit code 1, back off 9.[4](https://github.com/swiftotter/anomaly-detective-magento2/actions/runs/4226282278/jobs/7339563782#step:2:4)11 seconds before retry.
  /usr/bin/docker pull extdn/magento-copy-paste-detector-action:latest
  Error response from daemon: pull access denied for extdn/magento-copy-paste-detector-action, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: Docker pull failed with exit code 1
